// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: twoserver.proto

package twoserver_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for HelloServer service

type HelloServerService interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloReplay, error)
}

type helloServerService struct {
	c    client.Client
	name string
}

func NewHelloServerService(name string, c client.Client) HelloServerService {
	return &helloServerService{
		c:    c,
		name: name,
	}
}

func (c *helloServerService) SayHello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloReplay, error) {
	req := c.c.NewRequest(c.name, "HelloServer.SayHello", in)
	out := new(HelloReplay)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloServer service

type HelloServerHandler interface {
	SayHello(context.Context, *HelloRequest, *HelloReplay) error
}

func RegisterHelloServerHandler(s server.Server, hdlr HelloServerHandler, opts ...server.HandlerOption) error {
	type helloServer interface {
		SayHello(ctx context.Context, in *HelloRequest, out *HelloReplay) error
	}
	type HelloServer struct {
		helloServer
	}
	h := &helloServerHandler{hdlr}
	return s.Handle(s.NewHandler(&HelloServer{h}, opts...))
}

type helloServerHandler struct {
	HelloServerHandler
}

func (h *helloServerHandler) SayHello(ctx context.Context, in *HelloRequest, out *HelloReplay) error {
	return h.HelloServerHandler.SayHello(ctx, in, out)
}
