// Code generated by protoc-gen-go. DO NOT EDIT.
// source: threeserver.proto

package threeserver_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileRequest struct {
	Byte                 []byte   `protobuf:"bytes,1,opt,name=byte,proto3" json:"byte,omitempty"`
	Len                  int64    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07f24f3433afb6c, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetByte() []byte {
	if m != nil {
		return m.Byte
	}
	return nil
}

func (m *FileRequest) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

type FileStreamMsg struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileStreamMsg) Reset()         { *m = FileStreamMsg{} }
func (m *FileStreamMsg) String() string { return proto.CompactTextString(m) }
func (*FileStreamMsg) ProtoMessage()    {}
func (*FileStreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07f24f3433afb6c, []int{1}
}

func (m *FileStreamMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStreamMsg.Unmarshal(m, b)
}
func (m *FileStreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStreamMsg.Marshal(b, m, deterministic)
}
func (m *FileStreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStreamMsg.Merge(m, src)
}
func (m *FileStreamMsg) XXX_Size() int {
	return xxx_messageInfo_FileStreamMsg.Size(m)
}
func (m *FileStreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FileStreamMsg proto.InternalMessageInfo

func (m *FileStreamMsg) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "threeserver_proto.FileRequest")
	proto.RegisterType((*FileStreamMsg)(nil), "threeserver_proto.FileStreamMsg")
}

func init() { proto.RegisterFile("threeserver.proto", fileDescriptor_e07f24f3433afb6c) }

var fileDescriptor_e07f24f3433afb6c = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc9, 0x28, 0x4a,
	0x4d, 0x2d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x42, 0x16,
	0x8a, 0x07, 0x0b, 0x29, 0x19, 0x73, 0x71, 0xbb, 0x65, 0xe6, 0xa4, 0x06, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x24, 0x55, 0x96, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0,
	0x04, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x39, 0xa9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc,
	0x41, 0x20, 0xa6, 0x92, 0x36, 0x17, 0x2f, 0x48, 0x53, 0x70, 0x49, 0x51, 0x6a, 0x62, 0xae, 0x6f,
	0x71, 0xba, 0x90, 0x14, 0x17, 0x47, 0x5a, 0x66, 0x4e, 0x6a, 0x5e, 0x62, 0x2e, 0x44, 0x2b, 0x67,
	0x10, 0x9c, 0x6f, 0x14, 0xcb, 0xc5, 0x05, 0x56, 0x0c, 0xb6, 0x55, 0xc8, 0x9f, 0x8b, 0xdd, 0x3d,
	0xb5, 0x04, 0x24, 0x20, 0x24, 0xa7, 0x87, 0xe1, 0x1c, 0x3d, 0x24, 0xb7, 0x48, 0x29, 0xe0, 0x90,
	0x87, 0x5b, 0xab, 0xc4, 0xa0, 0xc1, 0x98, 0xc4, 0x06, 0x96, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0x41, 0xa2, 0x74, 0xef, 0x00, 0x00, 0x00,
}
