FROM golang AS builder

ENV GOPROXY https://goproxy.io
ENV GO111MODULE on

WORKDIR /go/cache
ADD go.mod .
ADD go.sum .
RUN go mod download

WORKDIR /go/release
ADD . .
RUN go build -o pweb main.go

FROM alpine

WORKDIR /app
COPY --from=builder /go/release/pweb /app/

CMD ["./pweb"]