basePath: /api/v1
definitions:
  model.ResponseData:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  description: API
  license: {}
  title: 测试
  version: "1.0"
paths:
  /test:
    post:
      description: gin添加Api测试
      parameters:
      - description: 参数
        in: formData
        name: param
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          schema:
            $ref: '#/definitions/model.ResponseData'
      summary: Test
swagger: "2.0"
