version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    network_mode: bridge
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    network_mode: bridge
    ports:
      - '3000:3000'
  web:
    container_name: web
    build: web
    restart: always
    network_mode: bridge
    command: ./pweb
    ports:
      - "8080:8080"