apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-service-deployment
  labels:
    app: zipkin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-service
  template:
    metadata:
      labels:
        app: zipkin-service
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim
          ports:
            - containerPort: 9411
---
kind: Service
apiVersion: v1
metadata:
  name: zipkin-service
spec:
  type: NodePort
  selector:
    app: zipkin-service
  ports:
    - protocol: TCP
      nodePort: 32223
      port: 9411
      targetPort: 9411